# fly.toml app configuration file generated for test-blue-smoke-97 on 2025-09-16T11:45:14+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-blue-smoke-97'
primary_region = 'syd'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile.web'

[deploy]
  release_command = '/bin/sh -c "python manage.py migrate --noinput && python manage.py djstripe_sync_models product price && python manage.py bootstrap_ecommerce && python manage.py validate_subscriptions"'

[env]
  DJANGO_SETTINGS_MODULE = 'test.settings_production'
  PORT = '8080'

[processes]
  app = '/code/start_all.sh'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

    [http_service.checks.headers]
      Host = 'localhost:8000'
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'data'
  destination = '/data'
