cli:
  app_directory: apps
  base_model: apps.utils.models.BaseModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: false
default_context:
  _pegasus_version: '2025.9'
  api_framework: drf
  author_name: Max
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: fly
  description: The most amazing SaaS application the world has ever seen!
  docker_setup: default
  domain_name: localhost:8000
  email: maxdavenport96@gmail.com
  enable_github_login: n
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: eporto2021
  include_static_files: n
  marketing_email_platform: none
  plugins:
  - chat
  post_process: y
  project_name: Eporto
  project_slug: Eporto
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  use_2fa: y
  use_admin_docs: y
  use_ai_rules_claude: n
  use_ai_rules_cursor: n
  use_ai_rules_junie: n
  use_api_auth: n
  use_api_keys: y
  use_async: y
  use_celery: y
  use_cloud_media_storage: n
  use_dark_mode: y
  use_debug_toolbar: n
  use_docker: y
  use_ecommerce_example: y
  use_examples: y
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: n
  use_teams_example: n
  use_translations: y
  use_wagtail: n
